export {default as back} from './back.svg'
export {default as book} from './book.svg'
export {default as calendar} from './calendar.svg'
export {default as cancel} from './cancel.svg'
export {default as caretdown} from './caret-down.svg'
export {default as dashboard} from './dashboard.svg'
export {default as filter} from './filter.svg'
export {default as happy} from './happy.svg'
export {default as leftarrow} from './left-arrow.svg'
export {default as list} from './list.svg'
export {default as minus} from './minus.svg'
export {default as more} from './more.svg'
export {default as next} from './next.svg'
export {default as pensmall} from './pen-small.png'
export {default as plus} from './plus.svg'
export {default as ruler} from './ruler.svg'
export {default as search} from './search.svg'
export {default as settings} from './settings.svg'
export {default as skill} from './skill.svg'
export {default as stopwatch} from './stopwatch.svg'
export {default as trash} from './trash.svg'
export {default as checkmark} from './checkmark.svg'
export {default as key} from './key.svg'
export {default as star} from './star.svg'
export {default as starfilled} from './star filled.svg'
export {default as logo} from './Journal Logo.PNG'