name: deploy-to-pages
on: [push]
jobs:
  do-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd journal/client
      - run: pwd
      - run: ls
      - run: npm install
      - run: npm run build
      - run: gh-pages -d build