name: deploy-to-pages
on: [push]
jobs:
  do-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        working-direcroty: ./client
        run: npm install
      - name: Build React Appliction
        working-direcroty: ./client
        run: npm run build
      - name: Deploy To Github Pages
        working-direcroty: ./client
        run: gh-pages -d build