name: deploy-to-pages
on: [push]
jobs:
  do-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install && npm install -g gh-pages
        working-directory: ./client
      - name: Build React Appliction
        run: npm run build
        working-directory: ./client
        env:
          CI: false
      - name: Deploy To Pages
        run: |
          mv client/build ./build \
          git stash push -u \
          git checkout gh-pages \
          git stash pop \
          cp -rf build ./ \
          git commit -am "auto action deployemnt" \
          git push
        